---
- hosts: prod
  tasks:
  - name: Delete content & directory
    ansible.builtin.file:
      state: absent
      path: /root/p2p-bot
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /root/p2p-bot
      state: directory
      mode: '0755'
  - name: Read-write git checkout from github
    ansible.builtin.git:
      repo: https://github.com/IgorTikush/binance-p2p-info-bot.git
      dest: /root/p2p-bot
  - name: Install packages based on package.json.
    yarn:
      path: /root/p2p-bot
  - name: stop p2p-bot
    command: 'pm2 delete index'
    ignore_errors: yes
  - name: run start prod
    command: bash -lc "cd /root/p2p-bot/src && pm2 start index.js"
